name: VillagerFriendlyFarms
version: '${project.version}'
main: com.example.villagerfriendlyfarms.VillagerFriendlyFarmsPlugin
api-version: '1.21'
description: A Minecraft Paper plugin for villager-friendly farming devices
author: Plugin Developer
website: https://example.com

permissions:
  villagerfriendlyfarms.create:
    description: Allows creating villager-friendly farms
    default: true
  villagerfriendlyfarms.use:
    description: Allows using villager-friendly farms
    default: true
  villagerfriendlyfarms.admin:
    description: Allows administrative access to all farms
    default: op
  villagerfriendlyfarms.reload:
    description: Allows reloading plugin configuration
    default: op
  villagerfriendlyfarms.give:
    description: Allows giving farm items to players
    default: op
  villagerfriendlyfarms.bypass.limits:
    description: Allows bypassing farm limits
    default: op
  villagerfriendlyfarms.access.all:
    description: Allows accessing any player's farms
    default: op

commands:
  vff:
    description: Main villager friendly farms command
    usage: /vff <reload|info|help|give|list>
    permission: villagerfriendlyfarms.use
    aliases: [villagerfarms, farms]